### ISSUE TITLE
mermaid-filterがインストールされますがGitHubActionsでは使用されません

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/coding-standards#188]
package.jsonの`install`スクリプトや、GitHubActions内でmermaid-filterがインストールされますが、package.jsonのスクリプト以外では使用されていないように見えます。（package.jsonのスクリプトはGitHubActionsから呼び出されません。）

必要ないのであれば、インストールコマンド（および使用している箇所）を削除する必要があると思います。

@ma91n どう思いますか？

**Comment by ma91n** [comment]
@ota-meshi OpenAPI規約でmermaid.js記法でUML表示させたかった際に必要だった記憶です。
uninstallして問題無さそうであれば削除します（ローカル環境構築がなぜか手間取っているので、それ待ち）

**Comment by ma91n** [comment]
## #200 結果

https://github.com/future-architect/coding-standards/pull/200 で対応


| 分類        | 対象   | 結果 | 📝            |
|-----------|------|----|---------------|
| Gitブランチ規約 | HTML | ✅️ | mermaid使用箇所なし |
|           | docx | ✅️ | 同上            |
| OpenAPI 2 | HTML | ❌️ |               |
|           | docx | ❌️ |               |
| OpenAPI 3 | HTML | ❌️ |               |
|           | docx | ❌️ |               |
| Slack利用規約 | HTML | ✅️ | mermaid使用箇所なし |
|           | docx | ✅️ | 同上            |

**Comment by ma91n** [comment]
いったん、以下のインストールは削除。
pandoc側のdockerにインストールが必要だが、インストールが失敗してしまうので、年内の対応は厳しいかも。

```
npm i --global mermaid-filter
```

**Comment by ota-meshi** [comment]
test-build-resources-with-pandocのjobのArtifactsに生成されたdocから格納できるようにしているので、これを使用してマージ前に生成物をチェックできます。

https://github.com/future-architect/coding-standards/actions/workflows/test-build-resources-with-pandoc.yml

**Comment by ma91n** [comment]
なるほど。💯 効率が高くできそうです。
otaさんが対応してくれる神対応してくれていそうなので、作業は待ちます

**Comment by ota-meshi** [comment]
いろいろ試してみた感じでは、mermaid-filter を使うのは厳しいかもしれませんね。
現在使用している、imageでは結局puppeteerのインストールで失敗してしまうようです。
imageのバージョンを上げた場合どうなるかは試してないので、その方向で手があるなら良いのですが。

**Comment by ota-meshi** [comment]
> 神対応してくれていそうなので、作業は待ちます

今ちょうど諦めたところでした 😅

**Comment by ota-meshi** [comment]
個人的な感想としてはSVG作るだけならpuppeteerはいらないと思うので、自作すれば簡単にできるのでは？とか思っていたりはします

**Comment by ota-meshi** [comment]
うまくいったと言っているコメントを参考にしてますが相変わらずうまくできません。

https://github.com/raghur/mermaid-filter/issues/17#issuecomment-977966355

**Comment by ota-meshi** [comment]
`mermaid-filter@1.4.5` を使用してなんとか動かすことができましたが、古いmermaidを使用するようで、文字化けしてしまいますね。。。

https://github.com/future-architect/coding-standards/actions/runs/12487775290


`nodejs`のv18使えればmermaid-filterの最新版使える気がしますが、apkの使い方に詳しくなくてどうすれば良いのか。。。

**Comment by ota-meshi** [comment]
nodejs 16にすれば新しいmermaid-filterが使えたみたいで、dockerのpandocを2.9から2.19までアップデートして試してみました。

文字化けの出方が変わりましたが文字化けは相変わらずのようです 😓 

https://github.com/future-architect/coding-standards/actions/runs/12488266181

**Comment by ota-meshi** [comment]
@ma91n 多分うまくいったので確認してください。
#208

**Comment by ma91n** [comment]
@ota-meshi 208確認しました！完璧です！
