### ISSUE TITLE
Gitブランチフロー規約からのリンク切れ

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/coding-standards#189]
https://future-architect.github.io/coding-standards/documents/forGitBranch/

からの下記のリンクは壊れているようです。

- [Markdown](https://github.com/future-architect/coding-standards/blob/master/documents/forGitBranch/Git%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%83%95%E3%83%AD%E3%83%BC%E8%A6%8F%E7%B4%84.md)
- [HTML](https://github.com/future-architect/coding-standards/blob/gh-pages/resources/Git%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%83%95%E3%83%AD%E3%83%BC%E8%A6%8F%E7%B4%84.html)
- [Word](https://github.com/future-architect/coding-standards/raw/gh-pages/resources/Git%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%83%95%E3%83%AD%E3%83%BC%E8%A6%8F%E7%B4%84.docx)

@ma91n 確認いただけますか？

**Comment by ota-meshi** [comment]
https://future-architect.github.io/coding-standards/documents/forSlack/

のこちらも。

[HTML](https://github.com/future-architect/coding-standards/blob/gh-pages/resources/slack_usage_guidelines.html)

**Comment by ota-meshi** [comment]
こちらも。
https://future-architect.github.io/coding-standards/documents/forMarkdown/

**Comment by ma91n** [comment]
@ota-meshi 合わせて確認します。
最近、PCを新調してローカル環境がうまく動作しないので、ボトルネックはそれです。😿

**Comment by ma91n** [comment]
UPDATING Now...

| 分類                                                                                          | 対象       | チェック | URL |
|---------------------------------------------------------------------------------------------|----------|------|-----|
| [Gitブランチフロー規約](https://future-architect.github.io/coding-standards/documents/forGitBranch/) | Markdown | ✅️   |     |
|                                                                                             | HTML     | ❌️   |     |
|                                                                                             | docx     | ❌️   |     |
| [Slack利用ガイドライン](https://future-architect.github.io/coding-standards/documents/forSlack/)    | Markdown | ✅️   |     |
|                                                                                             | ✅️       |      |     |
|                                                                                             | docx     | ✅️   |     |

**Comment by ma91n** [comment]
@ota-meshi リンク切れ、修正しました。

**Comment by ota-meshi** [comment]
ありがとうございます。
Job定義がゴチャついてきたので、追加で、shに切り出してそれを実行するように変更しました 😅
