### ISSUE TITLE
Gitブランチフロー規約を1ページで記述することを検討してください

### ISSUE THREAD

**Issue by ota-meshi** [future-architect/coding-standards#190]
現在、Gitブランチフロー規約は複数ページに分かれているようです。
これは印刷する際（ブラウザからPDF化するのも同様）に複数回行う必要があることを意味します。
Javaコーディング規約と同様に1ページで記述することはできませんか？

もし、現在のまま複数ページ構成を維持したい場合、
下記の問題を解決する方法を検討してください。

- メインページ以外の印刷が壊れる。
  例えば次のページで印刷をすると、最初に白いページが印刷されます。これはプリント用のCSSが1ページ構成を前提としているためだと思います。
   https://future-architect.github.io/coding-standards/documents/forGitBranch/merge_develop_to_feature.html
- メインページ以外のセクションが`<h2>`から始まる
   私たちのサイトはMarkdownで`<h1>`を記述すると`<h2>`になるように組まれています。
  これはPandocによって出力されるファイルに合わせているためで、`<h1>`（実際にはdocxの`<h1>`相当）をファイル全体のタイトルとせず、各セクションタイトルとして扱いたいためです。
  Gitブランチフロー規約のための特別な仕組みを構築する必要があると思います。
  または`<h1>`を`<h2>`扱いにするのをやめ、Pandocによるdocx出力の形式を変更することも検討できます。

@ma91n 検討よろしくお願いします。

**Comment by ma91n** [comment]
@ota-meshi 構成については印刷（PDF）要件を見落としていたので、単に思慮不足が原因でした。
今後の運用やアップグレード負荷を考えると、サイト的に亜種パターンを増やしたくないと思いますので、1ページで記述する方向を正面案として進めようと思います。
それでどうしても可読性が悪くなったり微妙だと、コンテンツの中身を変えたりする必要があるかと思うので、少し時間がかかる可能性があります。
おそらく、2025年1月には対応できるかと。

**Comment by ota-meshi** [comment]
👍
